apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    type: dummy-plan-scan-template
  name: dummy-plan-scan-template
  namespace: cas
spec:
  arguments:
    parameters:
    - name: scan-id
    - name: files-path
    - name: customer-modules
    - name: trigger-type
    - name: scan-configuration
    - name: excluded-paths
  entrypoint: main

  templates:
  - name: main
    outputs:
      parameters:
      - name: plan-scan-result
        valueFrom:
          parameter: '{{`steps.echo-output.outputs.result}}`}}'
    steps:
    - - name: echo-output
        template: echo-output

  - name: echo-output
    script:
      command:
      - node
      image: node:22-bookworm-slim
      source: |
        const output = {"scanners": [{"scannerName": "PIPEX", "shouldRun": false, "cloneType": "DIFF", "skipReason": "CUSTOMER_MODULE_DISABLED", "isAsync": false}, {"scannerName": "GITHISTORY", "shouldRun": false, "cloneType": "DIFF", "skipReason": "DISABLED_FOR_SCAN_TYPE", "isAsync": true}, {"scannerName": "IAC", "shouldRun": true, "cloneType": "FULL", "skipReason": null, "isAsync": false}, {"scannerName": "THIRDPARTY", "shouldRun": false, "cloneType": "DIFF", "skipReason": "CUSTOMER_MODULE_DISABLED", "isAsync": false}, {"scannerName": "CIMATCH", "shouldRun": false, "cloneType": "DIFF", "skipReason": "DISABLED_FOR_SCAN_TYPE", "isAsync": false}, {"scannerName": "DEPPY", "shouldRun": false, "cloneType": "DIFF", "skipReason": "DISABLED_FOR_SCAN_TYPE", "isAsync": false}, {"scannerName": "SECRETS", "shouldRun": false, "cloneType": "DIFF", "skipReason": "ddd", "isAsync": false}, {"scannerName": "SCA", "shouldRun": true, "cloneType": "DIFF", "skipReason": null, "isAsync": false}, {"scannerName": "ENRY", "shouldRun": false, "cloneType": "DIFF", "skipReason": "DISABLED_FOR_SCAN_TYPE", "isAsync": false}]}
        console.log(JSON.stringify(output))

  workflowMetadata:
    labelsFrom:
      name:
        expression: workflow.name
      uid:
        expression: workflow.uid
