apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: {{ .Values.namespaceOverride }}
  name: simple-encoder-decoder
  generateName: simple-encoder-decoder-
spec:
  serviceAccountName: {{ .Values.serviceAccount }}
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  workflowMetadata:
  entrypoint: main
  arguments:
    parameters:
      - name: my-list
        value: "[]"
    {{- if ne .Values.environmentType "local" }}
      - name: gcsBucket
        valueFrom:
          configMapKeyRef:
            name: cas-configmap
            key: WORKFLOWS_ARTIFACTS_BUCKET
            optional: false
    {{- end }}
  templates:
    - name: main
      outputs:
        parameters:
          - name: encoded-list
            valueFrom:
              parameter: "{{`{{steps.encode-list.outputs.parameters.encoded-list}}`}}"
          - name: decoded-list
            valueFrom:
              parameter:  "{{`{{steps.decode-list.outputs.parameters.decoded-list}}`}}"
      steps:
        - - name: encode-list
            template: encode-list
            arguments:
              parameters:
                - name: my-list
                  value: '{{ `{{workflow.parameters.my-list}}` }}'
        - - name: decode-list
            template: decode-list
            arguments:
              parameters:
                - name: encoded-list
                  value: '{{ `{{steps.encode-list.outputs.parameters.encoded-list}}` }}'
      retryStrategy:
        limit: 5
        backoff:
          duration: 2m
        expression: indexOf(lower(lastRetry.message), "pod was rejected") > -1  or indexOf(lower(lastRetry.message), "unknown (exit code 255)") > -1 or lastRetry.message == "PodInitializing"
    - name: encode-list
      inputs:
        parameters:
          - name: my-list
      script:
        image: alpine:latest
        command: [ sh ]
        source: |
          echo -n '{{`{{inputs.parameters.my-list}}`}}' | xxd -p | tr -d '\n' > /tmp/encoded-output.txt
      outputs:
        parameters:
          - name: encoded-list
            valueFrom:
              path: "/tmp/encoded-output.txt"
      retryStrategy:
        limit: 5
        backoff:
          duration: 2m
        expression: indexOf(lower(lastRetry.message), "pod was rejected") > -1  or indexOf(lower(lastRetry.message), "unknown (exit code 255)") > -1
    - name: decode-list
      inputs:
        parameters:
          - name: encoded-list
      script:
        image: alpine:latest
        command: [ sh ]
        source: |
          echo '{{`{{inputs.parameters.encoded-list}}`}}' | xxd -p -r > /tmp/decoded-output.json
      outputs:
        parameters:
          - name: decoded-list
            valueFrom:
              path: "/tmp/decoded-output.json"
      retryStrategy:
        limit: 5
        backoff:
          duration: 2m
        expression: indexOf(lower(lastRetry.message), "pod was rejected") > -1  or indexOf(lower(lastRetry.message), "unknown (exit code 255)") > -1