apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: {{ .Values.namespaceOverride }}
  name: simple-dummy
  generateName: simple-simple-dummy-
spec:
  serviceAccountName: {{ .Values.serviceAccount }}
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  workflowMetadata:
  entrypoint: main
  arguments:
    parameters:
      - name: json-string
        value: "{}"
    {{- if ne .Values.environmentType "local" }}
      - name: gcsBucket
        valueFrom:
          configMapKeyRef:
            name: cas-configmap
            key: WORKFLOWS_ARTIFACTS_BUCKET
            optional: false
    {{- end }}
  templates:
    - name: main
      outputs:
        parameters:
          - name: parsed-json
            valueFrom:
              expression:
                "let unparsed = steps['dummy'].outputs.parameters['json-string'];
                let parsed1 = replace(unparsed, '\\\\\\\\\\\\', '');
                let parsed2 = replace(parsed1, '[\"\\\\\"', '[');
                let parsed3 = replace(parsed2, '\\\\\"\"]', ']');
                let unifiedArray = fromJSON(parsed3); 
                let hasBlockPr = any(unifiedArray, {.block_pr}); 
                let hasBlockCicd = any(unifiedArray, {.block_cicd});
                toJSON({\"hasBlockPr\":hasBlockPr,\"hasBlockCicd\":hasBlockPr})"
      steps:
        - - name: dummy
            template: dummy
            arguments:
              parameters:
                - name: json-string
                  value: '{{ `{{workflow.parameters.json-string}}` }}'
      retryStrategy:
        limit: 5
        backoff:
          duration: 2m
        expression: indexOf(lower(lastRetry.message), "pod was rejected") > -1  or indexOf(lower(lastRetry.message), "unknown (exit code 255)") > -1 or lastRetry.message == "PodInitializing"
    - name: dummy
      inputs:
        parameters:
          - name: json-string
      script:
        image: alpine:latest
        command: [ sh ]
        source: |
          echo '{{ `{{inputs.parameters.json-string}}` }}' > /tmp/json-string.txt
      outputs:
        parameters:
          - name: json-string
            valueFrom:
              default: "{}"
              path: "/tmp/json-string.txt"
      retryStrategy:
        limit: 5
        backoff:
          duration: 2m
        expression: indexOf(lower(lastRetry.message), "pod was rejected") > -1  or indexOf(lower(lastRetry.message), "unknown (exit code 255)") > -1
