apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  labels:
    type: dummy-files-fetching-template
  name: dummy-files-fetching-template
  namespace: cas
spec:
  arguments:
    parameters:
    - name: scan-id
    - name: repositoryId
    - name: integrationType
    - name: flow
    - name: prFlow
      value: empty-value
    - name: branch
      value: empty-value
    - name: commit
      value: empty-value
    - name: pr
      value: empty-value
    - name: targetBranch
      value: empty-value
    - name: filesPath
      value: empty-value
    - name: filesCount
      value: empty-value
  entrypoint: main

  templates:
  - name: main
    outputs:
      parameters:
      - name: clone-path
        valueFrom:
          parameter: '{{`{{steps.echo-output.outputs.parameters.clone-path}}`}}'
      - name: diff-clone-path
        valueFrom:
          parameter: '{{`{{steps.echo-output.outputs.parameters.diff-clone-path}}`}}'
      - name: patch-file-mapping-path
        valueFrom:
          parameter: '{{`{{steps.echo-output.outputs.parameters.patch-file-mapping-path}}`}}'
      - name: files-list-path
        valueFrom:
          parameter: '{{`{{steps.echo-output.outputs.parameters.files-list-path}}`}}'
    steps:
    - - name: echo-output
        template: echo-output

  - name: echo-output
    outputs:
      parameters:
        - name: clone-path
          valueFrom:
            path: /tmp/clone-path.txt
        - name: diff-clone-path
          valueFrom:
            path: /tmp/diff-clone-path.txt
        - name: patch-file-mapping-path
          valueFrom:
            path: /tmp/patch-file-mapping-path.txt
        - name: files-list-path
          valueFrom:
            path: /tmp/files-list-path.txt
    script:
      command:
      - node
      image: node:22-bookworm-slim
      source: |
        const fs = require('fs')

        fs.writeFileSync('/tmp/clone-path.txt', 'clone-path-mock')
        fs.writeFileSync('/tmp/diff-clone-path.txt', 'diff-clone-path-mock')
        fs.writeFileSync('/tmp/patch-file-mapping-path.txt', 'patch-file-mapping/67e4eb4a6ad1cd261c20a504/7/7a32fcb06cc83a30f3022073d0965b8e31c83847/patch-file-mapping.json')
        fs.writeFileSync('/tmp/files-list-path.txt', 'files-list-path-mock')

  workflowMetadata:
    labelsFrom:
      name:
        expression: workflow.name
      uid:
        expression: workflow.uid
