apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: {{ .Values.namespaceOverride }}
  name: simple-input-enricher-actual
  generateName: simple-input-enricher-actual-
spec:
  workflowMetadata:
  entrypoint: main
  arguments:
    parameters:
      - name: workflow-input
        value: "123"
  templates:
    - name: main
      inputs:
        parameters:
          - name: workflow-input
            value: '{{ `{{workflow.parameters.workflow-input}}` }}'
      outputs:
        parameters:
          - name: my-step-output
            valueFrom:
              parameter: '{{ `{{steps.my-step.outputs.parameters.my-step-output}}` }}'
          - name: workflow-input-from-enriching
            valueFrom:
              parameter: '{{ `{{steps.enrich-input-param.outputs.parameters.workflow-input}}` }}'
#          - name: workflow-input-original
#            valueFrom:
#              parameter: '{{ `{{inputs.parameters.workflow-input}}` }}'
      steps:
        - - name: my-step
            template: my-step
            arguments:
              parameters:
                - name: my-step-input
                  value: '{{ `{{inputs.parameters.workflow-input}}` }}'
        - - name: enrich-input-param
            template: enrich-input-param
            arguments:
              parameters:
                - name: workflow-input
                  value: '{{ `{{inputs.parameters.workflow-input}}` }}'
    - name: my-step
      inputs:
        parameters:
          - name: my-step-input
      script:
        image: alpine:latest
        command: [ sh ]
        source: |
          echo -n 'some-output-for-{{`{{inputs.parameters.my-step-input}}`}}' > /tmp/my-step-output.txt
      outputs:
        parameters:
          - name: my-step-output
            valueFrom:
              path: "/tmp/my-step-output.txt"
    - name: enrich-input-param
      inputs:
        parameters:
          - name: workflow-input
      script:
        image: alpine:latest
        command: [ sh ]
        source: |
          echo '{{`{{inputs.parameters.workflow-input}}`}}' > /tmp/workflow-input.json
      outputs:
        parameters:
          - name: workflow-input
            valueFrom:
              path: "/tmp/workflow-input.json"