apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: {{ .Values.namespaceOverride }}
  name: simple-input-enricher
  generateName: simple-input-enricher-
spec:
  workflowMetadata:
  entrypoint: main
  arguments:
    parameters:
      - name: workflow-input
        value: "123"
  templates:
    - name: main
      inputs:
        parameters:
          - name: workflow-input
            value: '{{ `{{workflow.parameters.workflow-input}}` }}'
      outputs:
        parameters:
          - name: my-step-output
            valueFrom:
              parameter: '{{ `{{steps.my-step.outputs.parameters.my-step-output}}` }}'
          - name: workflow-input
            valueFrom:
              parameter: 'inputs.parameters.workflow-input'
      steps:
        - - name: my-step
            template: my-step
            arguments:
              parameters:
                - name: my-step-input
                  value: '{{ `{{inputs.parameters.workflow-input}}` }}'
    - name: my-step
      inputs:
        parameters:
          - name: my-step-input
      script:
        image: alpine:latest
        command: [ sh ]
        source: |
          echo -n 'some-output-for-{{`{{inputs.parameters.my-step-input}}`}}' > /tmp/my-step-output.txt
      outputs:
        parameters:
          - name: my-step-output
            valueFrom:
              path: "/tmp/my-step-output.txt"